import { createFileRoute } from '@tanstack/react-router'
import { DotMatrixText } from '../../components/primitives/DotMatrixText'

export const Route = createFileRoute('/blog/page1')({
  component: Page,
})

function Page() {
  return (
    <div className="animate-in fade-in duration-500 pb-20 p-10">
      <DotMatrixText size="xl" as="h1" glow="rust" className="mb-12">
        /BLOG/PAGE1
      </DotMatrixText>
      <p className="prose-cyber text-muted-foreground">
        This page was automatically generated by the terminal.
      </p>
    </div>
  )
}
