import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { createServerFn, useServerFn } from '@tanstack/react-start'
import { useState, useEffect, useRef } from 'react'
import { DotMatrixText } from '../components/primitives/DotMatrixText'
import { TerminalCursor } from '../components/primitives/TerminalCursor'
import { CyberButton } from '../components/primitives/CyberButton'
import { SectionLabel } from '../components/primitives/SectionLabel'
import { Divider } from '../components/primitives/Divider'
import { Card } from '../components/primitives/Card'

export const Route = createFileRoute('/')(  {
  component: Index,
})

const TERMINAL_LINES = [
  { prefix: '', text: ' ██╗  ██╗ █████╗ ██████╗ ███████╗██╗  ██╗' },
  { prefix: '', text: ' ██║  ██║██╔══██╗██╔══██╗██╔════╝██║  ██║' },
  { prefix: '', text: ' ███████║███████║██████╔╝███████╗███████║' },
  { prefix: '', text: ' ██╔══██║██╔══██║██╔══██╗╚════██║██╔══██║' },
  { prefix: '', text: ' ██║  ██║██║  ██║██║  ██║███████║██║  ██║' },
  { prefix: '', text: ' ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝' },
  { prefix: '', text: ' ' },
  { prefix: '>', text: ' INITIALIZING HARSH_OS V1.0...' },
  { prefix: '>', text: ' ACCESS GRANTED.' },
  { prefix: '>', text: " Type 'help' for a list of available commands." },
]

const terminalState = {
  lineIndex: 0,
  charIndex: 0,
  lines: [] as string[],
  done: false,
  commandHistory: [] as {type: 'command'|'output'|'error', text: string}[],
  inputValue: '',
}

const createPageFn = createServerFn({ method: 'POST' })
  .validator((d: string) => d)
  .handler(async ({ data }) => {
    const fs = await import('node:fs/promises')
    const path = await import('node:path')
    try {
      const safePath = data.replace(/[^a-zA-Z0-9_\-/]/g, '')
      if (!safePath) return { error: 'Invalid path' }
      
      const parts = safePath.split('/').filter(Boolean)
      const fileName = parts.pop() || 'index'
      const dirPath = path.join(process.cwd(), 'src/routes', ...parts)
      const fullPath = path.join(dirPath, `${fileName}.tsx`)
      
      await fs.mkdir(dirPath, { recursive: true })
      
      const componentName = (fileName.charAt(0).toUpperCase() + fileName.slice(1)).replace(/[^a-zA-Z]/g, '') || 'NewPage'
      
      // Calculate depth for component import
      const depth = parts.length + 1
      const importPath = '../'.repeat(depth) + 'components/primitives/DotMatrixText'
      
      // Fix route path format for TanStack router
      // e.g. blog/page_11 -> /blog/page_11
      // For index, we just use /
      let routePath = safePath === 'index' ? '/' : `/${safePath}`
      
      const content = `import { createFileRoute } from '@tanstack/react-router'
import { DotMatrixText } from '${importPath}'

export const Route = createFileRoute('${routePath}')({
  component: ${componentName},
})

function ${componentName}() {
  return (
    <div className="animate-in fade-in duration-500 pb-20 p-10">
      <DotMatrixText size="xl" as="h1" glow="rust" className="mb-12">
        /${safePath.toUpperCase()}
      </DotMatrixText>
      <p className="prose-cyber text-muted-foreground">
        This page was automatically generated by the terminal.
      </p>
    </div>
  )
}
`
      await fs.writeFile(fullPath, content)
      return { success: `Created new page at /${safePath}` }
    } catch (e: any) {
      return { error: e.message }
    }
  })

function Index() {
  const [lineIndex, setLineIndex] = useState(terminalState.lineIndex)
  const [charIndex, setCharIndex] = useState(terminalState.charIndex)
  const [lines, setLines] = useState<string[]>(terminalState.lines)
  const [done, setDone] = useState(terminalState.done)
  const navigate = useNavigate()
  const [commandHistory, setCommandHistory] = useState<{type: 'command'|'output'|'error', text: string}[]>(terminalState.commandHistory)
  const [inputValue, setInputValue] = useState(terminalState.inputValue)
  const inputRef = useRef<HTMLInputElement>(null)
  const terminalEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => { terminalState.lineIndex = lineIndex }, [lineIndex])
  useEffect(() => { terminalState.charIndex = charIndex }, [charIndex])
  useEffect(() => { terminalState.lines = lines }, [lines])
  useEffect(() => { terminalState.done = done }, [done])
  useEffect(() => { terminalState.commandHistory = commandHistory }, [commandHistory])
  useEffect(() => { terminalState.inputValue = inputValue }, [inputValue])

  useEffect(() => {
    terminalEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' })
  }, [lines, commandHistory, inputValue, charIndex, done])

  const createPage = useServerFn(createPageFn)

  const handleTerminalClick = () => {
    if (done && inputRef.current) {
      inputRef.current.focus()
    }
  }

  const handleCommand = async (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      const cmd = inputValue.trim()
      setInputValue('')
      
      if (!cmd) return
      
      const newHistory = [...commandHistory, { type: 'command' as const, text: `> ${cmd}` }]
      setCommandHistory(newHistory) // Update immediately for responsiveness
      
      const parts = cmd.split(/\s+/)
      const baseCmd = parts[0].toLowerCase()
      
      if (baseCmd === 'help') {
        setCommandHistory(h => [...h, { 
          type: 'output', 
          text: `Available directories:\n  - about\n  - skills\n  - projects\n  - blog\n  - contact\n\nUsage: cd <directory>\nUsage: mkdir <path> (Creates a new page)` 
        }])
      } else if (baseCmd === 'cd') {
        const dir = parts[1]?.toLowerCase()
        const validDirs: Record<string, string> = {
          'home': '/',
          'about': '/about',
          'skills': '/skills',
          'projects': '/projects',
          'blog': '/blog',
          'contact': '/contact'
        }
        
        if (!dir) {
          setCommandHistory(h => [...h, { type: 'error', text: 'cd: missing argument' }])
        } else if (dir === '..' || dir === '~') {
          navigate({ to: '/' })
        } else if (validDirs[dir]) {
          navigate({ to: validDirs[dir] })
        } else {
          setCommandHistory(h => [...h, { type: 'error', text: `cd: no such file or directory: ${dir}` }])
        }
      } else if (baseCmd === 'mkdir') {
        const dir = parts[1]
        if (!dir) {
          setCommandHistory(h => [...h, { type: 'error', text: 'mkdir: missing operand' }])
        } else {
          setCommandHistory(h => [...h, { type: 'output', text: `creating page ${dir}...` }])
          try {
            const res = await createPage({ data: dir })
            if (res.error) {
              setCommandHistory(h => [...h, { type: 'error', text: `mkdir error: ${res.error}` }])
            } else {
              setCommandHistory(h => [...h, { type: 'output', text: res.success || 'Done.' }])
            }
          } catch (err: any) {
            setCommandHistory(h => [...h, { type: 'error', text: `mkdir failed: ${err.message}` }])
          }
        }
      } else {
        setCommandHistory(h => [...h, { type: 'error', text: `command not found: ${baseCmd}. Type 'help' for available commands.` }])
      }
    }
  }

  useEffect(() => {
    if (lineIndex >= TERMINAL_LINES.length) {
      setDone(true)
      return
    }

    const currentLine = TERMINAL_LINES[lineIndex]
    const fullLine = currentLine.prefix + currentLine.text

    if (currentLine.prefix === '') {
      const timeout = setTimeout(() => {
        setLines((prev) => [...prev, fullLine])
        setLineIndex((l) => l + 1)
        setCharIndex(0)
      }, 0)
      return () => clearTimeout(timeout)
    }

    if (charIndex < fullLine.length) {
      const timeout = setTimeout(() => {
        setCharIndex((c) => c + 1)
      }, 25 + Math.random() * 20)
      return () => clearTimeout(timeout)
    }

    // Line complete — pause then move to next
    const pauseTimeout = setTimeout(() => {
      setLines((prev) => [...prev, fullLine])
      setLineIndex((l) => l + 1)
      setCharIndex(0)
    }, 200)
    return () => clearTimeout(pauseTimeout)
  }, [lineIndex, charIndex])

  const currentLine = lineIndex < TERMINAL_LINES.length
    ? (TERMINAL_LINES[lineIndex].prefix + TERMINAL_LINES[lineIndex].text).slice(0, charIndex)
    : ''

  return (
    <div>
      {/* ════════════ HERO ════════════ */}
      <section className="hero-section">
        {/* Accent tag above name */}
        <div className="flex items-center gap-3 mb-6">
          <span
            className="inline-block w-8 h-0.5 bg-accent-rust"
            style={{ boxShadow: '0 0 8px oklch(58% 0.16 42 / 0.4)' }}
          />
          <span className="font-mono text-xs text-accent-rust uppercase tracking-[0.2em]">
            Portfolio v1.0
          </span>
        </div>

        {/* Main name */}
        <div className="hero-title-wrapper">
          <DotMatrixText size="2xl" as="h1" glow="rust">
            HARSH
          </DotMatrixText>
        </div>

        {/* Subtitle with LED indicators */}
        <div className="flex items-center gap-3 mb-10">
          <h2 className="font-mono text-muted-foreground text-xs uppercase tracking-[0.18em] leading-relaxed">
            <span className="text-accent-rust">{'>'}</span> Hardware Engineer
            <span className="text-muted-foreground/40 mx-1.5">|</span>
            <span className="text-accent-blue">{'>'}</span> Software Developer
            <span className="text-muted-foreground/40 mx-1.5">|</span>
            <span className="text-accent-red">{'>'}</span> Maker
          </h2>
        </div>

        {/* Terminal block */}
        <div className="terminal-block h-[400px] flex flex-col" onClick={handleTerminalClick}>
          <div className="terminal-header shrink-0 z-20 pb-2 mb-2 border-b border-white/10">
            <span className="terminal-dot terminal-dot--red" />
            <span className="terminal-dot terminal-dot--yellow" />
            <span className="terminal-dot terminal-dot--green" />
            <span className="terminal-header-label">bash — system_init</span>
          </div>
          <div className="relative z-10 flex-1 overflow-y-auto scrollbar-thin text-oled-green font-mono flex flex-col">
            <div className="mt-auto flex flex-col">
              {lines.map((line, i) => (
              <div key={i} className="whitespace-pre-wrap leading-tight">
                <span className="text-accent-rust opacity-70">{line[0] === '>' ? '>' : ''}</span>
                <span>{line[0] === '>' ? line.slice(1) : line}</span>
              </div>
            ))}
            {!done && (
              <div className="whitespace-pre-wrap leading-tight">
                <span className="text-accent-rust opacity-70">{currentLine[0] === '>' ? '>' : ''}</span>
                <span>{currentLine[0] === '>' ? currentLine.slice(1) : currentLine}</span>
                <TerminalCursor className="text-oled-green" />
              </div>
            )}
            {done && (
              <div className="mt-2 text-oled-green">
                {commandHistory.map((item, i) => (
                  <div key={i} className={`whitespace-pre-wrap mb-1 leading-tight ${
                    item.type === 'error' ? 'text-accent-red' : 
                    item.type === 'command' ? 'text-oled-green' : 
                    'text-oled-cyan opacity-90'
                  }`}>
                    {item.text}
                  </div>
                ))}
                <div className="flex items-center mt-1">
                  <span className="text-accent-rust opacity-70 mr-2">{'>'}</span>
                  <input
                    ref={inputRef}
                    type="text"
                    value={inputValue}
                    onChange={(e) => setInputValue(e.target.value)}
                    onKeyDown={handleCommand}
                    className="flex-1 bg-transparent border-none outline-none text-oled-green font-mono leading-tight"
                    autoFocus
                    autoComplete="off"
                    spellCheck="false"
                  />
                </div>
              </div>
            )}
            <div ref={terminalEndRef} className="shrink-0 h-[30px]" />
            </div>
          </div>
        </div>

        {/* CTA Buttons */}
        <div className="flex flex-wrap gap-4">
          <CyberButton href="/projects" variant="rust">
            VIEW PROJECTS →
          </CyberButton>
          <CyberButton href="/blog" variant="blue">
            READ TRANSMISSIONS
          </CyberButton>
        </div>

        {/* Status chips */}
        <div className="status-row">
          <div className="status-chip">
            <span className="status-chip__dot status-chip__dot--online" />
            <span>Systems Online</span>
          </div>
          <div className="status-chip">
            <span className="status-chip__dot status-chip__dot--accent" />
            <span>Open to Collaborate</span>
          </div>
          <div className="status-chip">
            <span className="status-chip__dot" style={{ background: 'var(--color-accent-blue)', boxShadow: '0 0 6px oklch(52% 0.24 265 / 0.5)' }} />
            <span>Based in India</span>
          </div>
        </div>
      </section>

      <Divider />

      {/* ════════════ ABOUT BRIEF ════════════ */}
      <section className="py-10">
        <SectionLabel number="01" label="STATUS" />
        <div className="max-w-2xl space-y-5">
          <p className="text-lg leading-relaxed text-foreground">
            I build things that bridge the gap between <span className="text-accent-rust font-medium">bits</span> and <span className="text-accent-blue font-medium">atoms</span>.
            From embedded C firmware on bare metal to modern React web applications,
            I enjoy working across the entire stack.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Welcome to my personal databank — part portfolio, part engineering log.
            Explore my projects, read technical deep-dives, or get in touch for a collaboration.
          </p>
        </div>
      </section>

      <Divider />

      {/* ════════════ FEATURED PROJECTS ════════════ */}
      <section className="py-10">
        <SectionLabel number="02" label="FEATURED BUILDS" />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mt-2 stagger-fade-in">
          <Card className="group">
            <div className="flex items-start justify-between mb-3">
              <h3 className="font-display text-sm text-foreground group-hover:text-accent-rust transition-colors">
                CYBERDECK MK III
              </h3>
              <span className="font-mono text-xs text-muted-foreground bg-muted px-2 py-0.5">
                2025
              </span>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed mb-4">
              Custom mechanical keyboard & display in a 3D-printed chassis. Raspberry Pi 5, custom embedded Linux.
            </p>
            <div className="flex flex-wrap gap-1.5">
              {['Hardware', 'C++', 'Linux'].map((t) => (
                <span key={t} className="font-mono text-xs text-accent-rust/70 border border-accent-rust/20 px-1.5 py-0.5">
                  {t}
                </span>
              ))}
            </div>
          </Card>

          <Card className="group">
            <div className="flex items-start justify-between mb-3">
              <h3 className="font-display text-sm text-foreground group-hover:text-accent-blue transition-colors">
                NEURAL SYNTH ENGINE
              </h3>
              <span className="font-mono text-xs text-muted-foreground bg-muted px-2 py-0.5">
                2025
              </span>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed mb-4">
              Polyphonic hardware synthesizer using neural network waveform generation on FPGA.
            </p>
            <div className="flex flex-wrap gap-1.5">
              {['Verilog', 'DSP', 'FPGA'].map((t) => (
                <span key={t} className="font-mono text-xs text-accent-blue/70 border border-accent-blue/20 px-1.5 py-0.5">
                  {t}
                </span>
              ))}
            </div>
          </Card>
        </div>

        <div className="mt-6">
          <CyberButton href="/projects" variant="rust" className="!text-[10px]">
            ALL PROJECTS →
          </CyberButton>
        </div>
      </section>

      <Divider />

      {/* ════════════ QUICK LINKS / CAPABILITIES ════════════ */}
      <section className="py-10">
        <SectionLabel number="03" label="CAPABILITIES" />
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-2 stagger-fade-in">
          {[
            { label: 'Embedded C/C++', icon: '[C]' },
            { label: 'PCB Design', icon: '[P]' },
            { label: 'FPGA / Verilog', icon: '[F]' },
            { label: 'React / TS', icon: '[R]' },
            { label: 'Systems Design', icon: '[S]' },
            { label: '3D Fabrication', icon: '[3D]' },
          ].map((s) => (
            <div
              key={s.label}
              className="
                flex items-center gap-3 px-4 py-3
                border border-foreground/10 bg-foreground/[0.02]
                hover:border-accent-rust/40 hover:bg-foreground/[0.04]
                transition-all duration-200 cursor-default group
              "
            >
              <span className="text-accent-rust/60 text-base group-hover:text-accent-rust transition-colors">{s.icon}</span>
              <span className="font-mono text-xs uppercase tracking-wider text-foreground/80">{s.label}</span>
            </div>
          ))}
        </div>

        <div className="mt-6 flex gap-3">
          <CyberButton href="/skills" variant="blue" className="!text-[10px]">
            FULL SKILL MATRIX →
          </CyberButton>
          <CyberButton href="/contact" variant="rust" className="!text-[10px]">
            GET IN TOUCH
          </CyberButton>
        </div>
      </section>
    </div>
  )
}
