/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as BlogPage_1RouteImport } from './routes/blog/page_1'
import { Route as BlogPage1RouteImport } from './routes/blog/page1'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminWriteProjectRouteImport } from './routes/admin/write-project'
import { Route as AdminWriteRouteImport } from './routes/admin/write'
import { Route as AdminEditProjectIdRouteImport } from './routes/admin/edit-project/$id'
import { Route as AdminEditPostSlugRouteImport } from './routes/admin/edit-post/$slug'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPage_1Route = BlogPage_1RouteImport.update({
  id: '/blog/page_1',
  path: '/blog/page_1',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPage1Route = BlogPage1RouteImport.update({
  id: '/blog/page1',
  path: '/blog/page1',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWriteProjectRoute = AdminWriteProjectRouteImport.update({
  id: '/write-project',
  path: '/write-project',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWriteRoute = AdminWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditProjectIdRoute = AdminEditProjectIdRouteImport.update({
  id: '/edit-project/$id',
  path: '/edit-project/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditPostSlugRoute = AdminEditPostSlugRouteImport.update({
  id: '/edit-post/$slug',
  path: '/edit-post/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/admin/write': typeof AdminWriteRoute
  '/admin/write-project': typeof AdminWriteProjectRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/page1': typeof BlogPage1Route
  '/blog/page_1': typeof BlogPage_1Route
  '/project/$id': typeof ProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/edit-post/$slug': typeof AdminEditPostSlugRoute
  '/admin/edit-project/$id': typeof AdminEditProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/admin/write': typeof AdminWriteRoute
  '/admin/write-project': typeof AdminWriteProjectRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/page1': typeof BlogPage1Route
  '/blog/page_1': typeof BlogPage_1Route
  '/project/$id': typeof ProjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/edit-post/$slug': typeof AdminEditPostSlugRoute
  '/admin/edit-project/$id': typeof AdminEditProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/admin/write': typeof AdminWriteRoute
  '/admin/write-project': typeof AdminWriteProjectRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/page1': typeof BlogPage1Route
  '/blog/page_1': typeof BlogPage_1Route
  '/project/$id': typeof ProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/edit-post/$slug': typeof AdminEditPostSlugRoute
  '/admin/edit-project/$id': typeof AdminEditProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/admin/write'
    | '/admin/write-project'
    | '/blog/$slug'
    | '/blog/page1'
    | '/blog/page_1'
    | '/project/$id'
    | '/admin/'
    | '/blog/'
    | '/admin/edit-post/$slug'
    | '/admin/edit-project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/admin/write'
    | '/admin/write-project'
    | '/blog/$slug'
    | '/blog/page1'
    | '/blog/page_1'
    | '/project/$id'
    | '/admin'
    | '/blog'
    | '/admin/edit-post/$slug'
    | '/admin/edit-project/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/admin/write'
    | '/admin/write-project'
    | '/blog/$slug'
    | '/blog/page1'
    | '/blog/page_1'
    | '/project/$id'
    | '/admin/'
    | '/blog/'
    | '/admin/edit-post/$slug'
    | '/admin/edit-project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  SkillsRoute: typeof SkillsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogPage1Route: typeof BlogPage1Route
  BlogPage_1Route: typeof BlogPage_1Route
  ProjectIdRoute: typeof ProjectIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/page_1': {
      id: '/blog/page_1'
      path: '/blog/page_1'
      fullPath: '/blog/page_1'
      preLoaderRoute: typeof BlogPage_1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/page1': {
      id: '/blog/page1'
      path: '/blog/page1'
      fullPath: '/blog/page1'
      preLoaderRoute: typeof BlogPage1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/write-project': {
      id: '/admin/write-project'
      path: '/write-project'
      fullPath: '/admin/write-project'
      preLoaderRoute: typeof AdminWriteProjectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/write': {
      id: '/admin/write'
      path: '/write'
      fullPath: '/admin/write'
      preLoaderRoute: typeof AdminWriteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit-project/$id': {
      id: '/admin/edit-project/$id'
      path: '/edit-project/$id'
      fullPath: '/admin/edit-project/$id'
      preLoaderRoute: typeof AdminEditProjectIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit-post/$slug': {
      id: '/admin/edit-post/$slug'
      path: '/edit-post/$slug'
      fullPath: '/admin/edit-post/$slug'
      preLoaderRoute: typeof AdminEditPostSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminWriteRoute: typeof AdminWriteRoute
  AdminWriteProjectRoute: typeof AdminWriteProjectRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditPostSlugRoute: typeof AdminEditPostSlugRoute
  AdminEditProjectIdRoute: typeof AdminEditProjectIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminWriteRoute: AdminWriteRoute,
  AdminWriteProjectRoute: AdminWriteProjectRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditPostSlugRoute: AdminEditPostSlugRoute,
  AdminEditProjectIdRoute: AdminEditProjectIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  SkillsRoute: SkillsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogPage1Route: BlogPage1Route,
  BlogPage_1Route: BlogPage_1Route,
  ProjectIdRoute: ProjectIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
